server:
  port: 8050
spring:
  application:
    name: account
  datasource:
    name: ordering
    url: jdbc:mysql://localhost:3306/ordering?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: user
#    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.npy.entity